source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "7.1"

target "Bracelet" do
    pod 'MagicalRecord',            '~> 2.3.0'
    pod 'CocoaLumberjack',          '~> 2.2.0'
    pod 'MJExtension',              '~> 3.0.10'
    pod 'SRMonthPicker',            '~> 0.2.10'
    pod 'SDWebImage',               '~> 3.7.1'
    pod 'libPhoneNumber-iOS',       '~> 0.8.8'
    pod 'MJRefresh',                '~> 3.0.1'
    pod 'AFNetworking',             '~> 3.1.0'
    pod 'ZXingObjC',                '~> 3.0'
    pod 'Bugtags',                  '~> 1.2.6'
    pod 'Masonry',                  '~> 0.6.3'
    pod 'UMengAnalytics',           '~> 3.6.6'
    pod 'AliyunOSSiOS',             '~> 2.5.0'
    pod 'JPush-iOS-SDK',            '~> 2.1.7'
    pod 'TPKeyboardAvoiding',       '~> 1.3'
    pod 'MGSwipeTableCell',         '~> 1.5.5'
end